name: WakeUp Backend

on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"

jobs:
  wake_up_backend:
    runs-on: ubuntu-latest

    steps:
      - name: GET request to our backend
        env:  # Define an environment variable
          BACKEND_LINK: ${{ secrets.BACKEND_LINK }}
        run: curl $BACKEND_LINK
