name:
  WakeUp Backend
 
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"
 
      
jobs:
 
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    steps:
      - name: GET request to our backend
        run: curl ${{ vars.BACKEND_LINK }}
